[package]
name = "overlinejunior/hearts"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
licence = "MIT"
author = "Over"
exclude = ["selene.toml", "roblox.toml"]

[dependencies]
Signal = "sleitnick/signal@^1"
